image: node:latest
stages:
  - deploy
cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  only:
    - master
  before_script:
    - 'npm install'
  script:
    - 'npm run build'
  after_script:
    - './cf-cache-flush.sh'
  artifacts:
    paths:
      - public
variables:
  GIT_DEPTH: '1'
  CF_ZONE_ID: '26c20487321750ddce766cc1a83a6afa'

